Update MobileFuse SDK to v1.6.0
ChartBoost/chartboost-mediation-android-adapter-mobilefuse pull request #6
Opened 2023-08-16 18:12 UTC by tomaszbmf

+ Update MobileFuse SDK to v1.6.0
+ Init MobileFuse SDK in the Adapter setUp call

2023-08-17 17:34 UTC, cb-jpadilla commented on MobileFuseAdapter/src/main/java/com/chartboost/mediation/mobilefuseadapter/MobileFuseAdapter.kt
> +                    resumeOnce(Result.success(PartnerLogController.log(SETUP_FAILED)))
Let's pass a `Result.failure` here.
```suggestion
PartnerLogController.log(SETUP_FAILED)
resumeOnce(
    Result.failure(
        ChartboostMediationAdException(ChartboostMediationError.CM_INITIALIZATION_FAILURE_UNKNOWN)
    )
)
```

2023-08-17 17:35 UTC, chauduyphanvu requested changes
Besides @cb-jpadilla's point, please also update the CHANGELOG and README.

2023-08-18 08:03 UTC, tomaszbmf commented on MobileFuseAdapter/src/main/java/com/chartboost/mediation/mobilefuseadapter/MobileFuseAdapter.kt
> +                    resumeOnce(Result.success(PartnerLogController.log(SETUP_FAILED)))
Thanks, I added this change

2023-08-18 16:18 UTC, chauduyphanvu approved these changes
lgtm with a minor change. we'll run the code changes through certification. once everything looks good, they'll be released. thanks!

2023-08-18 16:18 UTC, chauduyphanvu commented on MobileFuseAdapter/src/main/java/com/chartboost/mediation/mobilefuseadapter/MobileFuseAdapter.kt
> +
Remove extra line

2023-08-18 16:38 UTC, tomaszbmf commented on MobileFuseAdapter/src/main/java/com/chartboost/mediation/mobilefuseadapter/MobileFuseAdapter.kt
> +
ok, done

2023-08-18 16:41 UTC, cb-jpadilla approved these changes
Looks good. Thank you for the changes. 👍🏼

2023-08-18 16:49 UTC, merged