Update MobileFuse SDK to v1.6.5
ChartBoost/chartboost-mediation-android-adapter-mobilefuse pull request #8
Opened 2023-12-04 13:52 UTC by tomaszbmf

Use the latest MobileFuse SDK 1.6.5 in the Adapter.

2023-12-08 18:00 UTC, cb-jpadilla requested changes
Minor Comment. Needs update to the README.md

2023-12-08 18:00 UTC, cb-jpadilla commented on CHANGELOG.md
> +### 4.1.6.5.0
There should be a README.md file that needs to be updated with this version as well.

2023-12-11 10:45 UTC, tomaszbmf commented
> Minor Comment. Needs update to the README.md

I missed it, thanks. I added the requested change.

2023-12-11 18:00 UTC, cb-jpadilla approved these changes
Thank you for the changes. Approved.

2023-12-11 18:21 UTC, merged